### ISSUE TITLE
Response time higher than 60sec

### ISSUE THREAD

**Issue by HijackHornet** [AnthonyRAFFY/scrappey_proxy#5]
Sorry it's me again.
I was wondering how do you do to add a cloudflare protected site into prowlarr considering scrappey take more than 60sec to respond.
I changed the timeout of the proxy to 180sec, but still in prowlarr when I try to add the indexer, after 60sec it shows "failed" while I see in the background that scrappey_proxy is waiting for the response. He finally get a positive response but too late. 
Did you face this issue?

**Comment by AnthonyRAFFY** [comment]
Hello,

I did not encounter the issue as in my case Scrappey usually respond in less than 10s. It sounds like the default timeout value for Prowlarr is 100s and [Prowlarr did not add a way to increase it](https://github.com/Prowlarr/Prowlarr/issues/586). 

Did you try to send the request directly from Scrappey request's builder ? Maybe you can tweak some options. You can also check if your proxy is not slowing down the whole process using the proxies provided by Scrappey. (But I doubt it is the case)

**Comment by HijackHornet** [comment]
Then maybe the issue is with my proxy I don't know. I added timestamps and it looks like between the time the request is sent to scrappey and the response there is 50sec if there is cloudflare. But it doesn't looks like prowlarr is getting the response as I'm still seeing the test running. A second request is then sent that also do nothing..
And in any case, the cookie should be store and provided instantly but it doesn't. I don't know what's messing with it.

**Comment by HijackHornet** [comment]
So I tried another site and it solves in 10sec.
However my prowlarr still says the test failed. I see in scrappey console it was solved and responded 200. But probably the cookie is not properly sent to prowlarr or something... At this point I'm out of ideas

**Comment by AnthonyRAFFY** [comment]
It is really weird, could you send the logs ?

Did you already add scrappey_proxy as an Indexer Proxy in Prowlarr ?

Did you add the right tags for your site ?

![Image](https://github.com/user-attachments/assets/4baa1e19-9285-41ad-a743-b0a531ae7aa9)

If you forgot to add your proxy for example, you will hit a cloudflare challenge again as it is not the right IP for the cf_clearance cookie.

**Comment by HijackHornet** [comment]
Wait. I need to add both the proxy and the scrappey "cloudflare" ?

**Comment by HijackHornet** [comment]
I'm sorry. I didn't see I needed to add the proxy as well in prowlarr... You wrote it so it's my fault for not reading correctly..

**Comment by HijackHornet** [comment]
It's working finally!
Thanks a lot for your help. I really appreciate it:)
